let coxsbazar = [
	{  
		name: 'Right Side Room with green View',
		place: 'coxbazar',
		id: 'coxbazar1',
		guests: '4',
		bedrooms: '2',
		bed: '2',
		bathrooms: '2',
		cost: '34',
		ratting: '4.8',
		rattingNumber: '20',
		description: 'Wif Air conditioning Kitchen',
		comfort: 'Cancellation fexibility availiable',
		image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
	},
	{  
		name: 'Presidential-Suite_Hotel-Sea-Crown',
		place: 'coxbazar',
		id: 'coxbazar3',
		guests: '2',
		bedrooms: '1',
		bed: '1',
		bathrooms: '1',
		cost: '14',
		ratting: '4.6',
		rattingNumber: '12',
		description:'Wif Air conditioning Kitchen',
		comfort: 'Cancellation fexibility availiable',
		image: 'https://hotelseacrownbd.com/wp-content/uploads/2017/07/Presidential-Suite_Hotel-Sea-Crown_Cox-Bazar-14-850x450.jpg'
	},
	{  
		name: 'Light House, full lighing view View',
		place: 'coxbazar',
		id: 'coxbazar2',
		guests: '5',
		bedrooms: '3',
		bed: '2',
		bathrooms: '2',
		cost: '35',
		ratting: '4.5',
		rattingNumber: '13',
		description: 'Wif Air conditioning Kitchen',
		comfort: 'Cancellation fexibility availiable',
		image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
	},
	{  
		name: 'See Nature and River',
		place: 'shrimongol',
		id: 'shrimongol',
		guests: '2',
		bedrooms: '1',
		bed: '1',
		bathrooms: '1',
		cost: '64',
		ratting: '4.3',
		rattingNumber: '22',
		description: 'Wif Air conditioning Kitchen',
		comfort: 'Cancellation fexibility availiable',
		image: 'https://content.r9cdn.net/rimg/himg/63/1d/48/hotelsdotcom-602556224-96dd0d83_w-719266.jpg?width=1004&crop=true&caller=HotelDetailsPhoto'
	},
	{  
		name: 'Left Room with see View and swimming pool',
		place: 'shrimongol',
		id: 'shrimongol2',
		guests: '6',
		bedrooms: '3',
		bed: '1',
		bathrooms: '1',
		cost: '16',
		ratting: '4.7',
		rattingNumber: '45',
		description: 'Wif Air conditioning Kitchen',
		comfort: 'Cancellation fexibility availiable',
		image: 'https://q-xx.bstatic.com/xdata/images/hotel/max1000/135525705.jpg?k=36c07c8e53e74fffa2bcb47184ec418c258050e1ee4e4c556e5b1d1b770c4358'
	},
	{  
		name: 'See Srimongol Beach',
		place: 'shrimongol',
		id: 'shrimongol3',
		guests: '8',
		bedrooms: '2',
		bed: '4',
		bathrooms: '2',
		cost: '64',
		ratting: '4.8',
		rattingNumber: '20',
		description: 'Wif Air conditioning Kitchen',
		comfort: 'Cancellation fexibility availiable',
		image: 'https://images.trvl-media.com/hotels/22000000/21300000/21294800/21294712/476b1e8c_z.jpg'
	},
	{  
		name: 'Resort Font View',
		place: 'bandarbone',
		id: 'bandarbone',
		guests: '4',
		bedrooms: '2',
		bed: '2',
		bathrooms: '2',
		cost: '34',
		ratting: '4.8',
		rattingNumber: '18',
		description:'Wif Air conditioning Kitchen',
		comfort: 'Cancellation fexibility availiable',
		image: 'https://i.ytimg.com/vi/o16I3-7RKNU/maxresdefault.jpg'
	},
	{  
		name: 'See high tower and sunset View',
		place: 'bandarbone',
		id: 'bandarbone2',
		guests: '5',
		bedrooms: '3',
		bed: '2',
		bathrooms: '2',
		cost: '35',
		ratting: '4.5',
		rattingNumber: '13',
		description: 'Wif Air conditioning Kitchen',
		comfort: 'Cancellation fexibility availiable',
		image: 'https://www.holidayinnresortbd.com/images/65804917_2643500789062443_4821177970322309120_o.jpg'
	},
	{  
		name: 'Soil House and see sunset and sunrise view',
		place: 'bandarbone',
		id: 'bandarbone3',
		guests: '2',
		bedrooms: '1',
		bed: '1',
		bathrooms: '1',
		cost: '64',
		ratting: '4.3',
		rattingNumber: '22',
		description: 'Wif Air conditioning Kitchen',
		comfort: 'Cancellation fexibility availiable',
		image: 'https://avijatrik.org/wp-content/uploads/2019/12/24131549_540713996262587_1530231626330895928_n-870x555.jpg'
	}

]
export default coxsbazar;
